name: Publish development application

env:
  NAME: hello-world-streamlit
  NAMESPACE: cads-apps-dev
  APP_PATH: /c3s-applications/hello-world-streamlit/
  IMAGE_TAG: latest
  VALUES_FILE: values.dev.yaml

on:
  push:
    branches: [ "main" ]
    tags:
    - '*'

jobs:
  build_and_push:
    name: Build and push image to Harbor
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v3
      with:
        registry: eccr.ecmwf.int
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - uses: actions/checkout@v4

    - name: Set release environment variables
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      run: |
        echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "NAMESPACE=cads-apps-prod" >> $GITHUB_ENV
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with: 
        context: .
        platforms: linux/amd64
        push: true
        tags: "eccr.ecmwf.int/c3s-applications/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}"
  
  deployment:
    name: Deploy application with helm
    needs:
      - build_and_push
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: Set release environment variables
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      run: |
        echo "VALUES_FILE=values.prod.yaml" >> $GITHUB_ENV
        sed -i "s/DUMMY_IMAGE_TAG/${GITHUB_REF#refs/*/}/g" environments/values.prod.yaml
        
    - name: 'Add repo'
      run: helm repo add --username ${{ secrets.HARBOR_USERNAME  }} --password ${{ secrets.HARBOR_PASSWORD  }} c3s-applications https://eccr.ecmwf.int/chartrepo/c3s-applications
    - name: "Update Helm Chart"
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml && chmod 400 kubeconfig.yaml;
        echo "EXCUTING: helm upgrade -n $NAMESPACE $NAME c3s-applications/c3s-applications || helm install -n $NAMESPACE $NAME c3s-applications/c3s-applications --values environments/$VALUES_FILE"
        helm upgrade -n $NAMESPACE $NAME c3s-applications/c3s-applications || helm install -n $NAMESPACE $NAME c3s-applications/c3s-applications --values environments/$VALUES_FILE
      env:
        KUBECONFIG: kubeconfig.yaml
    - name: "Force update of pods"
      run: kubectl delete pods -l app=hello-world
      env:
        KUBECONFIG: kubeconfig.yaml   
      