name: Publish application

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    name: Build and push image to Harbor
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v3
      with:
        registry: eccr.ecmwf.int
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with: 
        context: .
        platforms: linux/amd64
        push: true
        tags: eccr.ecmwf.int/c3s-applications/${{ github.event.repository.name }}:latest
        build-args: |
          public_url=$APP_PATH

      
      
      
      