name: Publish application

on:
  push:
    branches: [ "main" ]

jobs:
  # build_and_push:
  #   name: Build and push image to Harbor
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: docker/login-action@v3
  #     with:
  #       registry: eccr.ecmwf.int
  #       username: ${{ secrets.HARBOR_USERNAME  }}
  #       password: ${{ secrets.HARBOR_PASSWORD }}

  #   - uses: actions/checkout@v4
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3
  #     with:
  #       buildkitd-flags: --debug
  #   - name: Build the Docker image
  #     uses: docker/build-push-action@v5
  #     with: 
  #       context: .
  #       platforms: linux/amd64
  #       push: true
  #       tags: eccr.ecmwf.int/c3s-applications/${{ github.event.repository.name }}:latest
  #       build-args: |
  #         public_url=$APP_PATH
  
  update_helm_chart_values:
    # needs:
    #   - build_and_push
    name: Deploy helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: c3s-applications/helm-chart
          ref: main
          token: ${{  secrets.TOKEN  }}
      - name: 'Setup git config'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: "Update values"
        run: ls; touch temp.txt; git add temp.txt; git commit -m"temp"
      - name: "Push back to main"
        run: git push origin main
      



      
      
      
      